### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by christoph-buente** [manojsharmatestla/tracker-auto#1]
Hey Manoj,

this is the output of the latest execution:

`~/Projects/tracker-auto/test (coding-challange)*$ mvn clean package -Dmaven.skip.test=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for test.com:test:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 20, column 18
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 55, column 18
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building test 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ test ---
[INFO] Deleting /Users/cristophbunte/Projects/tracker-auto/test/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 12 source files to /Users/cristophbunte/Projects/tracker-auto/test/target/classes
[WARNING] /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/utils/web/WebDriverManager.java: /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/utils/web/WebDriverManager.java uses or overrides a deprecated API.
[WARNING] /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/utils/web/WebDriverManager.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/pages/BasePage.java: /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/pages/BasePage.java uses unchecked or unsafe operations.
[WARNING] /Users/cristophbunte/Projects/tracker-auto/test/src/main/java/com/test/automation/framework/pages/BasePage.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/cristophbunte/Projects/tracker-auto/test/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ test ---
[INFO] No tests to run.
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 17, 2018 11:49:10 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFORMATION: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
/private/var/folders/jd/286g775144q57zl15zg4f6lc0000gp/T/1523958550196-0/chromedriver: /private/var/folders/jd/286g775144q57zl15zg4f6lc0000gp/T/1523958550196-0/chromedriver: cannot execute binary file
Apr 17, 2018 11:49:31 AM org.openqa.selenium.os.OsProcess checkForError
SCHWERWIEGEND: org.apache.commons.exec.ExecuteException: Process exited with an error: 126 (Exit value: 126)
[ERROR] Tests run: 6, Failures: 3, Errors: 0, Skipped: 3, Time elapsed: 24.314 s <<< FAILURE! - in TestSuite
[ERROR] initializeDriver(com.test.automation.tests.LiveIntentPageTest)  Time elapsed: 23.296 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'ChrisBookPro-927.local', ip: 'fe80:0:0:0:aebc:32ff:fec1:4fe9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_161'
Driver info: driver.version: ChromeDriver
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:13121/status] to be available after 20002 ms
Caused by: java.util.concurrent.TimeoutException

[ERROR] beforeClass(com.test.automation.tests.LiveIntentPageTest)  Time elapsed: 23.468 s  <<< FAILURE!
java.lang.NullPointerException
	at com.test.automation.tests.LiveIntentPageTest.beforeClass(LiveIntentPageTest.java:25)

[ERROR] destroyDriver(com.test.automation.tests.LiveIntentPageTest)  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LiveIntentPageTest.beforeClass:25 » NullPointer
[ERROR]   LiveIntentPageTest>BaseTest.destroyDriver:28 » NullPointer
[ERROR]   LiveIntentPageTest>BaseTest.initializeDriver:20 » WebDriver Timed out waiting ...
[INFO] 
[ERROR] Tests run: 5, Failures: 3, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.305 s
[INFO] Finished at: 2018-04-17T11:49:32+02:00
[INFO] Final Memory: 22M/318M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project test: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/cristophbunte/Projects/tracker-auto/test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
~/Projects/tracker-auto/test (coding-challange)*$ 
`

**Comment by manojsharmatestla** [comment]
Fixed
